### ISSUE TITLE
XCode 8.3.2 (8E2002) 

### ISSUE THREAD

**Issue by volkergraf** [TheMattRay/cordova-plugin-wkwebviewxhrfix#1]
Hello

I Addes both Plugins to our Projekt .. 

cordova-plugin-wkwebview-engine 1.1.3 "Cordova WKWebView Engine"
cordova-plugin-wkwebviewxhrfix 0.1.0 "WKWebView XHR Fix"

But trying to access anything via File-Url does not work . like

  $.get('file://P307.cimd.json', function(data) {
                iclInterface.cimd = JSON.parse(data);
                alert("Did load JSOn File");
            }, 'text')
            .fail(function(data) {alert(data);
            console.error("FAIL");
            });

in this case I get no output ..

**Comment by TheMattRay** [comment]
Hey, @volkergraf! Sorry for the delayed response. My guess is that the path is incorrect. Is the file you are accessing placed in your www folder or a subfolder?

**Comment by volkergraf** [comment]
The file is placed in the www-Folder . 

I created a new Project 

> cordova create meh
> cd meh
> cordova plugin add cordova-plugin-wkwebview-engine
> cordova plugin add https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix
> cordova platform add ios

and placed my  foo.

json-file in the www-Folder (www/foo.json)

in www/js/index.js I did the follwing:

```
  receivedEvent: function(id) {
         ............................
             console.log('Received Event: ' + id);
             alert("Now trying to load file://foo.json");
             $.get('file://foo.json', function(data) {
                  cimd = JSON.parse(data);
                  alert("Did load JSOn File");
             }, 'text') .fail(function(data) {alert(data);console.error(data)});
```

and added   

```
 <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8/jquery.min.js"</script> 
 <meta http-equiv="Content-Security-Policy" content="
           default-src 'self' blob: data: gap: 'unsafe-eval';
           script-src * 'self' http://* 'unsafe-eval';
           style-src * 'self' 'unsafe-inline' http://*;  
           child-src blob: gap://ready; 
           connect-src * 'self' https://* http://*;">
```

to the index.html

Running the Application gives me the following Message:

> [Error] {readyState: 0, setRequestHeader: function, getAllResponseHeaders: function, getResponseHeader: function, overrideMimeType: function, …}
> 	(anonyme Funktion) (index.js:49)
> 	l (jquery.min.js:2:17002)
> 	fireWith (jquery.min.js:2:17785)
> 	T (jquery.min.js:2:81029)
> 	r (jquery.min.js:2:86565)
> [Error] Failed to load resource: file is directory (foo.json, line 0)
> 

Using file://foo.json results in  

> Failed to load resource: file is directory (foo.json, line 0)

Putting the file in e.g. www/img and unsing file://img/foo.json results in 

> Failed to load resource: The requested URL was not found on this server.

Any Ideas what's wrong ?

I attached the the modified files, if you like to test it.

[proj.zip](https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix/files/1047866/proj.zip)

**Comment by volkergraf** [comment]
Hmm it seems that NOT USING the file:// Prefix seems to fix the Problem .. 
The Problem I'm having NOW is that I have to load a few PNG-Files using MapBoxGL using 

```
map.loadImage('file://car16.png', (error, image) => {
                    if (error) {
                        alert("Car16 image not loaded");

                        console.error(error);
                        console.error(error);
                        throw error;
                    }
                    map.addImage('car16', image);
                });

```
If I use **map.loadImage('file://car16.png', (error, image)** 

> Failed to load resource: file is directory _file://car16.png/_ (it seems to append a /)


using **map.loadImage('car16.png', ....**

i get 

> Failed to load resource file:///var/containers/Bundle/Application/BF9BAC41-E003-4C56-ADBA-B72A0615E123/Cordova%20Vector%20ICL.app/www/car16.png: The requested URL was not found on this server.


I really don't know what the Problem might be .. 

Is it possible that I am trying to load toe Files to early or too late .. or something like that ?

It definitively seems to be an iOS Problem .. I tried the whole thing with Android and a local Safari and it worked finde .. 

Thanx in Advance

**Comment by TheMattRay** [comment]
Closed since it’s pretty old
