### ISSUE TITLE
CDVPlugin class WKWebViewXHRFix (pluginName: wkwebviewxhrfix) does not exist.

### ISSUE THREAD

**Issue by volkergraf** [TheMattRay/cordova-plugin-wkwebviewxhrfix#2]
Hell 

I tried to use your plugin by simply doing the following steps:

```
cordova create meh
cd meh
cordova plugin add 
cordova plugin add cordova-plugin-wkwebview-engine
cordova plugin add https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix

...

open platforms/ios/HelloCordova.xcodeproj
```

set the Team etc. and run it .. 

Starting the "App" I get the Following output on the Console:

2017-06-07 12:42:39.503145+0200 HelloCordova[1100:213448] Apache Cordova native platform version 4.4.0 is starting.
2017-06-07 12:42:39.504039+0200 HelloCordova[1100:213448] Multi-tasking -> Device: YES, App: YES
2017-06-07 12:42:39.510696+0200 HelloCordova[1100:213448] 

```
Started backup to iCloud! Please be careful.
Your application might be rejected by Apple if you store too much data.
For more information please read "iOS Data Storage Guidelines" at:
https://developer.apple.com/icloud/documentation/data-storage/
To disable web storage backup to iCloud, set the BackupWebStorage preference to "local" in the Cordova config.xml file
2017-06-07 12:42:39.582128+0200 HelloCordova[1100:213448] Could not signal service com.apple.WebKit.WebContent: 113: Could not find specified service
2017-06-07 12:42:39.583733+0200 HelloCordova[1100:213448] Could not signal service com.apple.WebKit.Networking: 113: Could not find specified service
2017-06-07 12:42:39.584235+0200 HelloCordova[1100:213448] CDVWKWebViewEngine will reload WKWebView if required on resume
2017-06-07 12:42:39.584301+0200 HelloCordova[1100:213448] Using WKWebView
2017-06-07 12:42:39.585179+0200 HelloCordova[1100:213448] [CDVTimer][handleopenurl] 0.101030ms
2017-06-07 12:42:39.587276+0200 HelloCordova[1100:213448] [CDVTimer][intentandnavigationfilter] 2.018988ms
2017-06-07 12:42:39.587426+0200 HelloCordova[1100:213448] [CDVTimer][gesturehandler] 0.082016ms
2017-06-07 12:42:39.587475+0200 HelloCordova[1100:213448] CDVPlugin class WKWebViewXHRFix (pluginName: wkwebviewxhrfix) does not exist.
2017-06-07 12:42:39.587504+0200 HelloCordova[1100:213448] [CDVTimer][wkwebviewxhrfix] 0.036955ms
2017-06-07 12:42:39.587538+0200 HelloCordova[1100:213448] [CDVTimer][TotalPluginStartup] 2.490997ms
```

Any Ideas ?

Would it suffice to simply put the lines: 

 ```
 @try {
            [configuration.preferences setValue:@TRUE forKey:@"allowFileAccessFromFileURLs"];
        }
        @catch (NSException *exception) {}
        
        @try {
            [configuration setValue:@TRUE forKey:@"allowUniversalAccessFromFileURLs"];
        }
        @catch (NSException *exception) {}
```

in CDVWKWebViewEngine.m after

` configuration.allowsInlineMediaPlayback = [settings cordovaBoolSettingForKey:@"AllowInlineMediaPlayback" defaultValue:NO];
`

**Comment by TheMattRay** [comment]
Just asking - did you perform a build using `cordova build ios`?

**Comment by volkergraf** [comment]
Yes =)

**Comment by pvdyck** [comment]
same here, same error but only on ios9, ios10 is ok
is it related to => http://stackoverflow.com.mevn.net/questions/44841134/cordova-wkwebview-issue-in-ios-9-but-not-ios10?rq=1 ?

**Comment by litoarias** [comment]
The problem persists in iOS 9 and iOS 10.
Another question, this access to the `[configuration.preferences setValue: @TRUE forKey: @ "allowFileAccessFromFileURLs" attributes; ` is approved 
 by apple when the application is released in the store?
The category runs perfect, but the exception the console log!! And question by apple guide lines security..
Thanks in advanced!!

**Comment by RileyDavidson-Evans** [comment]
I'm having the same issue , any updates here @litoarias @pvdyck

**Comment by pvdyck** [comment]
latest version solved the issues ( local xhr ) => https://forum.ionicframework.com/t/wkwebview-v3-0-0/82814/14

**Comment by gabrielsscavalcante** [comment]
Any answer about this problem? I'm having the same issue.

**Comment by diogeneshamilton** [comment]
Me as well- judging by this thread, might have been fixed but seems to have cropped up again.

**Comment by michielsebille** [comment]
Hi there, any solution on this problem. We are also having this issue.

**Comment by Keatooon** [comment]
Having the same issue:

"CDVPlugin class WKWebViewXHRFix (pluginName: wkwebviewxhrfix) does not exist"

Although in the console it displays this error, does it actually affect the app behaviour? For me everything works fine though, and this plugin solved the xhr issues.

**Comment by mluis** [comment]
Having the same issue..

**Comment by Faksprod** [comment]
Same error message in the Xcode console:

"CDVPlugin class WKWebViewXHRFix (pluginName: wkwebviewxhrfix) does not exist"

But local XHR works well... Should we take care of this message?

**Comment by globules-io** [comment]
Same issue here and it makes my app not working in the simulator but works on device and we need simulator to take screenshots Any idea how to fix this?

**Comment by mrayonnaise** [comment]
Feel free to submit a PR

**Comment by globules-io** [comment]
@mrayonnaise would if I knew what to fix

**Comment by TheMattRay** [comment]
That’s fair! Didn’t mean that as snide as it may have come across. I will
take a long-overdue look later today.

**Comment by globules-io** [comment]
Only thing I see is WKWebViewXHRFix vs CDVWKWebViewXHRFix in plugin.xml in feature. Testing now.

**Comment by globules-io** [comment]
So far I've removed your plugin and added the code directly to cordova-plugin-wkwebview-engine to see the result.
The error in the log is gone but for me the result stays the same, the app works when tested with a real device but it does not when tested with the simulator (files aren't loaded). Not sure where go to from here... 
Also note that I'm using cordova-plugin-wkwebview-file-xhr@2.1.2

**Comment by globules-io** [comment]
Ok I've found my problem, It refuses to load a sound file we have "click.mp3" but this only affects the simulator. So I'm kind of hijacking this thread I apologize cause I'm mixing 2 issues:

1- Your plugin works but generates an error in the log about CDVPlugin not found
2- Loading .mp3 files from the www folder does not work for some reason in the simulator (The resource was requested insecurely)

**Comment by TheMattRay** [comment]
No worries - you’re trying to get this working so I don’t blame you.

**Comment by adadgio** [comment]
I had the same issue and solved it installing : cordova plugin add cordova-plugin-wkwebview-engine. Apparently this plugin needs to be installed for the fix to work.

Dont't forget to add ALL this in your config: 

<platform name="ios">
..........[other code]
        <feature name="CDVWKWebViewEngine">
            <param name="ios-package" value="CDVWKWebViewEngine" />
        </feature>
        <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
        <preference name="WKWebViewOnly" value="true" />
    </platform>

**Comment by adadgio** [comment]
I had the same issue and solved it installing : cordova plugin add cordova-plugin-wkwebview-engine. Apparently this plugin needs to be installed for the fix to work.

Dont't forget to add ALL this in your config: 

```
<platform name="ios">
      ......
        <feature name="CDVWKWebViewEngine">
            <param name="ios-package" value="CDVWKWebViewEngine" />
        </feature>
        <preference name="CordovaWebViewEngine" value="CDVWKWebViewEngine" />
        <preference name="WKWebViewOnly" value="true" />
 </platform>
```

**Comment by MattSynaptic** [comment]
I'm still getting this. Has anyone figured out a resolution?

**Comment by globules-io** [comment]
https://github.com/globules-io/cordova-plugin-ios-xhr
