### ISSUE TITLE
can't build ionic app - 'CDVWKWebViewEngine.h' file not found

### ISSUE THREAD

**Issue by leabdalla** [TheMattRay/cordova-plugin-wkwebviewxhrfix#4]
Hi, I'm trying to build Ionic 4 app with this plugin, but I'm getting this error:

    /Users/myuser/Library/Developer/Xcode/DerivedData/myapp-giqixmsbhehpswfduojlqgwhobgy/Build/Intermediates.noindex/myapp.build/Debug-iphonesimulator/myapp.build/Objects-normal/x86_64/CDVWKWebViewEngine+FileXhrFix.d --serialize-diagnostics
    /Users/myuser/Library/Developer/Xcode/DerivedData/myapp-giqixmsbhehpswfduojlqgwhobgy/Build/Intermediates.noindex/myapp.build/Debug-iphonesimulator/myapp.build/Objects-normal/x86_64/CDVWKWebViewEngine+FileXhrFix.dia -c
    /Users/myuser/dev/myapp/myapp-ionic/platforms/ios/myapp/Plugins/cordova-plugin-wkwebviewxhrfix/CDVWKWebViewEngine+FileXhrFix.m -o
    /Users/myuser/Library/Developer/Xcode/DerivedData/myapp-giqixmsbhehpswfduojlqgwhobgy/Build/Intermediates.noindex/myapp.build/Debug-iphonesimulator/myapp.build/Objects-normal/x86_64/CDVWKWebViewEngine+FileXhrFix.o
    In file included from /Users/myuser/dev/myapp/myapp-ionic/platforms/ios/myapp/Plugins/cordova-plugin-wkwebviewxhrfix/CDVWKWebViewEngine+FileXhrFix.m:9:
    /Users/myuser/dev/myapp/myapp-ionic/platforms/ios/myapp/Plugins/cordova-plugin-wkwebviewxhrfix/CDVWKWebViewEngine+FileXhrFix.h:9:9: fatal error:
          'CDVWKWebViewEngine.h' file not found
    #import "CDVWKWebViewEngine.h"
            ^~~~~~~~~~~~~~~~~~~~~~
    1 error generated.

    ** BUILD FAILED **

For reference, here is my `ionic info`

    Ionic:

       Ionic CLI                     : 5.4.2 (/Users/myuser/.nvm/versions/node/v10.16.3/lib/node_modules/ionic)
       Ionic Framework               : @ionic/angular 4.11.7
       @angular-devkit/build-angular : 0.801.3
       @angular-devkit/schematics    : 8.1.3
       @angular/cli                  : 8.1.3
       @ionic/angular-toolkit        : 2.1.1

    Cordova:

       Cordova CLI       : 9.0.0 (cordova-lib@9.0.1)
       Cordova Platforms : android 8.1.0, browser 6.0.0, ios 5.1.1
       Cordova Plugins   : cordova-plugin-ionic-keyboard 2.2.0, cordova-plugin-ionic-webview 4.1.3, (and 16 other plugins)

    Utility:

       cordova-res : 0.6.0 (update available: 0.8.1)
       native-run  : 0.2.8 (update available: 0.3.0)

    System:

       Android SDK Tools : 26.1.1 (/Users/myuser/Library/Android/sdk)
       ios-deploy        : 1.9.4
       ios-sim           : 8.0.2
       NodeJS            : v10.16.3 (/Users/myuser/.nvm/versions/node/v10.16.3/bin/node)
       npm               : 6.13.2
       OS                : macOS Catalina
       Xcode             : Xcode 11.2.1 Build version 11B500

**Comment by TheMattRay** [comment]
Hey there!

With the newer offering of Capacitor, I highly recommend using it instead of Cordova if only for the fact that it was built from the ground up to use the new WKWebView and would this not need this plugin.

That being said, you may need to remove the plugin, remove the platform (iOS), ensure the folder is gone in “platforms”, and then add the platform and plugin again. It’s indicating that it isn’t finding the header file where it is expected. 

Thanks!

Matt

**Comment by prateekjeetsingh** [comment]
Hello,

I am also facing the same issue. The header file is not in the hierarchy if you check in the code.

Or do I have to install the cordova-plugin-wkwebview-engine in addition to this plugin?
Regards
Prateek Jeet Singh

**Comment by jhainaua** [comment]
For anyone coming across this issue in the future--installing cordova-plugin-wkwebview-engine in addition to this plugin fixed the problem for me. Thank you @prateekjeetsingh for the suggestion!

**Comment by prateekjeetsingh** [comment]
Hello,

Yes I did make progress on Matt’s plugin .
His plugin is fix to the original cordova plugin.

So you need add both the plugins at the same time to your cordova mobile application. I was earlier only adding Matt’s plugin and it wasn’t working.

However, I can’t rely on Matt’s correction. I would suggest you to use ionic cordova plugin alone. This plugin has the webkit and the resolution to the local CORS problem. You can find this plugin below:
https://github.com/ionic-team/cordova-plugin-ionic-webview.git

You will have to enable CORS in the system that you are trying to accessas the backend for your mobile applications. For example: we are using SAP OData services to retrieve data. So we need to enable CORS on our entry point to SAP system.

Regards
Prateek Jeet Singh

**Comment by jhainaua** [comment]
@prateekjeetsingh, thank you! I will try this other plugin.

**Comment by CurtisMorice** [comment]
> For anyone coming across this issue in the future--installing cordova-plugin-wkwebview-engine in addition to this plugin fixed the problem for me. Thank you @prateekjeetsingh for the suggestion!

The above worked and as well I installed this plugin to address apples new warning about WKWebview. 
https://github.com/TheMattRay/cordova-plugin-wkwebviewxhrfix
