### ISSUE TITLE
Fix for Cordova-ios@6.0.0

### ISSUE THREAD

**Issue by nintendowii111** [TheMattRay/cordova-plugin-wkwebviewxhrfix#6]
Needs to be updated for new Cordova iOS release!

**Comment by kokitang** [comment]
Just update all CDVWKWebViewEngine to CDVWebViewEngine, and set the CDVWebViewEngine.h in CordovaLib.xcodeproj from Private to Public

**Comment by jay34fr** [comment]
Hi all,
I also need this plugin to be compatible with Cordova iOS@6.0.0.
Without this plugin, I have a white screen after the splash screen...

**Comment by jay34fr** [comment]
> Just update all CDVWKWebViewEngine to CDVWebViewEngine, and set the CDVWebViewEngine.h in CordovaLib.xcodeproj from Private to Public

Hi @kokitang , please, how did you do that ? Directly in the plugin ? In Xcode ? In my app code ?
Thx in advance for your help.

**Comment by kokitang** [comment]
@jay34fr

For
> Just update all CDVWKWebViewEngine to CDVWebViewEngine

You can do it directly in the plugin or in Xcode.
Doing it in the plugin you may need to clone the repository and change the config.xml to let Cordova use your local plugin instead of the plugin on npm.  But, be noticed, using the local plugin will lead to the loss of further updates of the plugin.
Doing it in Xcode is the quickest way but you will lose the changes if you reinstall the platform/plugin. 

and for
> set the CDVWebViewEngine.h in CordovaLib.xcodeproj from Private to Public

You can do this in Xcode, and the changes will lose when reinstall/update the ios platform.

**Comment by jay34fr** [comment]
Thx @kokitang for your answer.
So for the change in the plugin I just need to rename :

		<header-file src="src/ios/CDVWKWebViewEngine+FileXhrFix.h" />
		<source-file src="src/ios/CDVWKWebViewEngine+FileXhrFix.m" />

to

		<header-file src="src/ios/CDVWebViewEngine+FileXhrFix.h" />
		<source-file src="src/ios/CDVWebViewEngine+FileXhrFix.m" />

in the plugin.xml

Then I have to rename both files in src/ios and to edit them ? 

Thx again.

**Comment by kokitang** [comment]
@jay34fr 
Sorry for the late response, you also need to replace all occurrence of `CDVWKWebViewEngine` to `CDVWebViewEngine` in the plugin's .h&.m sourcecode.

E.g. 
In `CDVWebViewEngine+FileXhrFix.m` (if you changed the name), change 
`@implementation CDVWKWebViewEngine (FileXhrFix)` 
to 
`@implementation CDVWebViewEngine (FileXhrFix)`

and do it in the same way in other occurrences.

**Comment by jay34fr** [comment]
Thx again !
I will give a try asap.

**Comment by cfremgen** [comment]
> @jay34fr
> Sorry for the late response, you also need to replace all occurrence of `CDVWKWebViewEngine` to `CDVWebViewEngine` in the plugin's .h&.m sourcecode.
> 
> E.g.
> In `CDVWebViewEngine+FileXhrFix.m` (if you changed the name), change
> `@implementation CDVWKWebViewEngine (FileXhrFix)`
> to
> `@implementation CDVWebViewEngine (FileXhrFix)`
> 
> and do it in the same way in other occurrences.

This solution does not work, since it requires cordova-plugin-wkwebview-engine which is no longer supported.

https://cordova.apache.org/announcements/2020/06/01/cordova-ios-release-6.0.0.html

> Due to this change, the cordova-plugin-wkwebview-engine plugin is obsolete and will not work with this release. If you have this plugin installed, it is safe to remove with cordova plugin remove cordova-plugin-wkwebview-engine.

Fundamentally this plugin needs to change to toggle the settings:
allowFileAccessFromFileURLs
allowUniversalAccessFromFileURLs

On the native Cordova WKWebView.

**Comment by jay34fr** [comment]
I think the developer is not working on this plugin anymore.... maybe someone will work on a fork one ?

**Comment by TheMattRay** [comment]
You are correct - if someone wants to take it over I am happy to transfer.

**Comment by lehizojie** [comment]
I am working on a fork for this. I am happy to take it on if no one has already. Let me know.

**Comment by jay34fr** [comment]
Thx in advance @lehizojie !

**Comment by lovelyelfpop** [comment]
How to set the CDVWebViewEngine.h in CordovaLib.xcodeproj from Private to Public?
Am I doing it wrong? @lehizojie
![截屏2020-07-15 上午7 01 33](https://user-images.githubusercontent.com/5656924/87554597-e54c9300-c6e6-11ea-9b2e-b013c85ec8fe.png)

**Comment by kokitang** [comment]
@lovelyelfpop You already set it to public

**Comment by TheMattRay** [comment]
Here is this one that the guy copied and worked on: https://github.com/globules-io/cordova-plugin-ios-xhr

Wish he had forked and submitted a PR but /shrug

**Comment by globules-io** [comment]
Sorry @TheMattRay, was in a hurry and couldn't adapt your plugin to work . Hence the merge over a new name. If you ever fix this plugin and add 
```
 <preference name="allowFileAccessFromFileURLs" value="true|false" />
 <preference name="allowUniversalAccessFromFileURLs" value="true|false" />
```
I'll then kill this plugin... Besides, there is none of your original code remaining...

**Comment by Mapiac** [comment]
@globules-io @TheMattRay @kokitang @lehizojie @jay34fr 
Just a heads up you might use the seemingly far more maintained and active Ionic wkwebview plugin (we don't use Ionic but we use the plugin). Any reason you all don't? Want to save you some time here if I can

**Comment by AraHovakimyan** [comment]
Fix for Cordova iOS 6.x.x+

`cordova plugin add https://github.com/AraHovakimyan/cordova-plugin-wkwebviewxhrfix`

It works fine for me.

**Comment by TheMattRay** [comment]
Don’t forget - anyone can submit a PR
