### ISSUE TITLE
Cannot load resources in device.

### ISSUE THREAD

**Issue by csantanu** [TheMattRay/cordova-plugin-wkwebviewxhrfix#8]
For our ebook (which loads epub files from remote server) app, we have to migrate to WKWebview and we are using this plugin along with cordova-plugin-wkwebview-engine. Our cordova iOS is 5.1.1.

Everything builds well, no CORS issue etc. in the simulator. The library and ePUB files also load perfectly in the simulator.

But, when the app is run from device (iPhone XR, 14.2), the app runs well Except the library. None of the book cover images are shown and the epub files are downloading (evident from console) but when opened shows a blank page. The safari web inspector says cannot load resources, operation not permitted.

Any help will be highly appreciated.

**Comment by AraHovakimyan** [comment]
Try adding also another plugin cordova-plugin-wkwebview-file-xhr.
I think this will help to solve that issue

`https://github.com/oracle/cordova-plugin-wkwebview-file-xhr`
